### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by arlando** [jessaustin/gulp-nav#6]
It seems this doesn't work on Windows. I can only produce flat navigational or none at all. Sucks, because this was working great on Mac :cry:.

I am using Windows 8, gulp-nav 0.1.11, and Node version 5.9.1. Everything on  my Mac is mostly the same except the OS.

**Comment by jessaustin** [comment]
I suspect this may be due to the assumption that `'/'` is the directory separator. I rarely code on Windows. When I fix this, could you test it for me?

**Comment by arlando** [comment]
I was looking at that, it seems they added path.sep which will automatically detect path separation for the platform: https://nodejs.org/api/path.html#path_path_sep. I will test it for you. I don't have much experience with coffee script but can look through the built gulp-nav.js. Thank you!

**Comment by arlando** [comment]
It seems to be generating the right paths for the html files, except when I inspect nav.root it isn't the correct root , it is the last inspected file.

**Comment by jessaustin** [comment]
OK I've published another version. Please use the following commands to test in a previously-empty directory:
```bash
npm i gulp-nav
cd node_modules/gulp-nav
npm i
npm t
```
Please send me the output from the last command. This should help zero in on what to fix.

**Comment by arlando** [comment]
Hi @jessaustin,

I was unable to install on Windows:

```
$ npm i
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\...\gulp-nav-tests\node_modules\gulp-nav\npm-debug.log
```

**Comment by arlando** [comment]
More information from npm-debug.log

```
14952 verbose stack TypeError: Cannot read property 'target' of null
14952 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\lib\install\filter-invalid-actions.js:24:35)
14952 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
14952 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
14952 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
14952 verbose stack     at Object.Installer.computeLinked (C:\Program Files\nodejs\node_modules\npm\lib\install.js:411:41)
14952 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
14952 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
14952 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
14952 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\lib\install\diff-trees.js:50:3)
14952 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
```

**Comment by arlando** [comment]
Ok I installed by just cloning your repo and running the tests. This works on my Mac, but npm scripts sometimes don't work nicely on Windows:

```
$ npm t

> gulp-nav@0.1.15 pretest C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav
> npm run prepublish


> gulp-nav@0.1.15 prepublish C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav
> coffee --compile --map gulp-nav.coffee web-path.coffee


> gulp-nav@0.1.15 test C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav
> istanbul cover --print none gulp test | faucet && istanbul report text-summary

No coverage information was collected, exit without writing coverage information
C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\node_modules\.bin\gulp.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at runFn (C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\node_modules\istanbul\lib\util\file-matcher.js:68:16
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
npm ERR! Test failed.  See above for more details.
``` 

However I was able to just do gulp test:

```
$ gulp test
[11:25:31] Requiring external module coffee-script/register
[11:25:34] Using gulpfile ~\OSS\gulp-nav-raw\gulp-nav\gulpfile.coffee
[11:25:34] Starting 'test'...
TAP version 13
# Self-Stream
ok 1 Nav should have this title.
not ok 2 Nav should have this href.
  ---
    operator: equal
    expected: 'b.html'
    actual:   '..\\..\\..\\..\\..\\latin\\b.html'
  ...
ok 3 Nav should be active.
# Parent-Stream
not ok 4 Nav should have this title.
  ---
    operator: equal
    expected: 'Latin'
    actual:   null
  ...
not ok 5 Nav should have this href.
  ---
    operator: equal
    expected: '.'
    actual:   undefined
  ...
ok 6 Nav shouldn't be active.
# Grandparent-Stream
C:\Users\****\OSS\gulp-nav-raw\gulp-nav\gulp-nav.js:187
      title: nav.title,
                ^

TypeError: Cannot read property 'title' of null
  at navInContext (C:\Users\*****\OSS\gulp-nav-raw\gulp-nav\gulp-nav.js:187:17)
  at Object.defineProperties.parent.get [as parent] (C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\gulp-nav.js:194:18)
  at Test.<anonymous> (C:\Users\****\gulp-nav-raw\gulp-nav\gulpfile.coffee:48:34)
  at Test.bound [as _cb] (C:\Users***\OSS\gulp-nav-raw\gulp-nav\node_modules\tape\lib\test.js:61:32)
  at Test.run (C:\Users\u6033930\OSS\gulp-nav-raw\gulp-nav\node_modules\tape\lib\test.js:80:10)
  at Test.bound [as run] (C:\***\OSS\gulp-nav-raw\gulp-nav\node_modules\tape\lib\test.js:61:32)
  at Immediate.next [as _onImmediate] (C:\***\OSS\gulp-nav-raw\gulp-nav\node_modules\tape\lib\results.js:70:15)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

This looks helpful.

**Comment by arlando** [comment]
See my pr #7 with potential fix :100:
